version: '3.6'

#Docker services
services:
  db:
    image: postgres:12
    restart: always
    ports:
      - "5557:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./.containers/postgres:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=db
      - PGDATA=/var/lib/postgresql/data/db-files/
    networks:
      - agilize

  api:
    build:
      context: .
    entrypoint: /usr/sbin/entrypoint.local
    ports:
      - "9990:80"
    networks:
      - agilize
    volumes:
      - .:/var/www
    depends_on:
      - db

  rabbitmq:
    image: rabbitmq:3.11.3-management
    container_name: 'rabbitmq'
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - ./.docker/rabbitmq/data/:/var/lib/rabbitmq/
      - ./.docker/rabbitmq/log/:/var/log/rabbitmq
      - ./.docker/rabbitmq/enabled_plugins:/usr/lib/rabbitmq/enabled_plugins
    networks:
      - agilize

#Docker networks
networks:
  agilize:
    name: agilize_agilize
    driver: bridge

#Docker volumes
volumes:
  db_data:
    driver: local
